apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-s1bi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-s1bi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-s1bi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-s1bi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-s1bi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tvhz-tenant/rhtap-demo-app/hacbs-test-project-s1bi@sha256:ff5fc2f2d77bc91649897ec60171c6f6ebf02db97af818f1cac8b69d07ef61d7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
